services:
  redis:
    image: redis:7-alpine
    container_name: car-rental-redis
    ports:
      - "6379:6379"

  api:
    build:
      context: ./services/api
    container_name: car-rental-api
    env_file:
      - .env
    environment:
      APP_ENV: ${APP_ENV:-development}
      DATABASE_URL: ${DATABASE_URL:-sqlite:////data/rental.db}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      PAYMENT_QUEUE_NAME: ${PAYMENT_QUEUE_NAME:-payments:pending}
      NOTIFICATION_QUEUE_NAME: ${NOTIFICATION_QUEUE_NAME:-notifications:pending}
      INTERNAL_SERVICE_TOKEN: ${INTERNAL_SERVICE_TOKEN:-change-me}
      NOTIFICATION_SERVICE_URL: ${NOTIFICATION_SERVICE_URL:-http://notification-service:8002}
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:3000}
      SEED_DEMO_DATA: ${SEED_DEMO_DATA:-true}
    volumes:
      - api_data:/data
    ports:
      - "8000:8000"
    depends_on:
      - redis

  payment-service:
    build:
      context: ./services/payment
    container_name: car-rental-payment
    env_file:
      - .env
    environment:
      APP_ENV: ${APP_ENV:-development}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      PAYMENT_QUEUE_NAME: ${PAYMENT_QUEUE_NAME:-payments:pending}
      API_INTERNAL_URL: http://api:8000/internal/payments/process-result
      INTERNAL_SERVICE_TOKEN: ${INTERNAL_SERVICE_TOKEN:-change-me}
      SIMULATED_PAYMENT_DELAY_SECONDS: ${SIMULATED_PAYMENT_DELAY_SECONDS:-4}
    ports:
      - "8001:8001"
    depends_on:
      - redis
      - api

  notification-service:
    build:
      context: ./services/notification
    container_name: car-rental-notification
    env_file:
      - .env
    environment:
      APP_ENV: ${APP_ENV:-development}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      NOTIFICATION_QUEUE_NAME: ${NOTIFICATION_QUEUE_NAME:-notifications:pending}
    ports:
      - "8002:8002"
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
    container_name: car-rental-frontend
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  api_data:
